use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :justice_dialer, JusticeDialer.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: "justice-dialer.gigalixirapp.com", port: 4000],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/manifest.json",
  server: true

config :libcluster,
  topologies: [
    k8s_example: [
      strategy: Cluster.Strategy.Kubernetes,
      config: [
        kubernetes_selector: "${LIBCLUSTER_KUBERNETES_SELECTOR}",
        kubernetes_node_basename: "${LIBCLUSTER_KUBERNETES_NODE_BASENAME}"
      ]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Use Mailgun
config :justice_dialer, JusticeDialer.Mailer,
  adapter: Swoosh.Adapters.Mailgun,
  api_key: "${MAILGUN_KEY}",
  domain: "${MAILGUN_DOMAIN}"

# Update secret
config :justice_dialer, update_secret: "${UPDATE_SECRET}"

config :actionkit,
  base: "${AK_BASE}",
  username: "${AK_USERNAME}",
  password: "${AK_PASSWORD}"

config :justice_dialer,
  mongodb_username: "${MONGO_USERNAME}",
  mongodb_seeds: ["${MONGO_SEED_1}", "${MONGO_SEED_2}"],
  mongodb_password: "${MONGO_PASSWORD}",
  mongodb_port: "${MONGO_PORT}"

config :ex_twilio,
  account_sid: "${TWILIO_ACCOUNT_SID}",
  auth_token: "${TWILIO_AUTH_TOKEN}"

config :justice_dialer,
  two_factor_from_number: "${TWO_FACTOR_FROM_NUMBER}",
  two_factor_callback_url: "${TWO_FACTOR_CALLBACK_URL}",
  airtable_key: "${AIRTABLE_KEY}",
  airtable_base: "${AIRTABLE_BASE}"

config :rollbax,
  access_token: "${ROLLBAR_ACCESS_TOKEN}",
  environment: "production"
